name: Python Game CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt || true  # skip if empty

    - name: Lint with flake8
      run: |
        # Lint all .py files, max line length 88 (Black-compatible)
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-line-length=88 --statistics

    - name: Run unit tests
      run: |
        python -m unittest discover -s . -p "test_wump.py"
